#!/bin/sh


res=$(echo " Lock| Logout|勒 Reboot| Shutdown" | rofi -sep "|" -dmenu -p 'Power Menu' -theme "$XDG_CONFIG_HOME/qtile/scripts/powermenu-theme.rasi" -width 12 -lines 4 -eh 2 -location 3 -yoffset 23 -padding 15 -font "JetBrainsMono Nerd Font 11")
 
case $res in
	*"Lock"*) sh -c "xscreensaver-command -lock" ;;
	*"Logout"*) qtile-cmd -o cmd -f shutdown ;;
	*"Reboot"*) systemctl reboot ;;
	*"Shutdown"* ) systemctl poweroff ;;
	*) exit 0 ;;
esac
