#!/bin/bash


res=$(echo "🔒Lock|⇥ Logout|↺ Reboot|⏻ Shutdown" | rofi -sep "|" -dmenu -p 'Power Menu' -theme "~/.config/qtile/scripts/powermenu-theme.rasi" -width 12 -lines 4 -eh 2 -location 3 -yoffset 23 -padding 15 -font "Hack Nerd Font Mono 10")
 
if [[ $res == *"Lock"* ]]; then
	sh -c "xscreensaver-command -lock"
elif [[ $res == *"Logout"* ]]; then
	qtile-cmd -o cmd -f shutdown 
elif [[ $res == *"Reboot"* ]]; then
	systemctl reboot
elif [[ $res == *"Shutdown"* ]]; then
	systemctl poweroff
fi
exit 0
